---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
- name: Delete default nginx configuration
  file: path=/etc/nginx/sites-enabled/default state=absent